// Tests for the GENERATED dispatch-rules matrix (`hopper-dispatch --rules`)
// and its injection into the scaffold (.hopper/DISPATCH.md + AGENTS.md pointer).
// Anchor: tests/unit/rules.test.js

import { test } from 'node:test';
import { strict as assert } from 'node:assert';
import { renderRulesMarkdown } from '../../cli/src/rules.js';
import { listAdapters } from '../../cli/src/vendors/index.js';
import { buildScaffoldFiles } from '../../cli/src/scaffold.js';
import { parseAgentsContent, resolveVendor } from '../../cli/src/agents.js';

test('renderRulesMarkdown lists every registered vendor with a matrix row', () => {
  const md = renderRulesMarkdown({ version: '9.9.9' });
  assert.match(md, /GENERATED, do not hand-edit/);
  assert.match(md, /Generated by hopper v9\.9\.9/);
  for (const v of listAdapters()) {
    assert.match(md, new RegExp(`\\|\\s*${v}\\s*\\|`), `matrix must have a row for ${v}`);
  }
});

test('renderRulesMarkdown derives cells from the live adapters (no drift)', () => {
  const md = renderRulesMarkdown();
  // codex: model now forwarded via -m, cwd --cd, reasoning enumerated
  assert.match(md, /codex.*`-m <model>`.*`--cd`/);
  // grok: reasoning clamped vocabulary low/medium/high, perms --always-approve
  assert.match(md, /grok.*low\/medium\/high.*--always-approve/);
  // kimi: no cwd flag, perms not argv-enforced
  assert.match(md, /kimi.*not argv-enforced.*none/);
  // claude: --add-dir for cwd
  assert.match(md, /claude.*`--add-dir`/);
  // contract section documents the max-effort default + idle/ceiling model
  assert.match(md, /defaults to `xhigh`/);
  assert.match(md, /idle \+ ceiling/);
});

test('renderRulesMarkdown is deterministic (no timestamps)', () => {
  assert.equal(renderRulesMarkdown({ version: '1.2.3' }), renderRulesMarkdown({ version: '1.2.3' }));
});

test('codex P2a: full-access perms show shared bypass flags (grok bypassPermissions not hidden)', () => {
  const md = renderRulesMarkdown();
  assert.match(md, /grok.*bypassPermissions.*--always-approve/, 'grok perms must reveal bypassPermissions, not just the delta');
  assert.match(md, /read-only is \*\*not always argv-enforceable\*\*/, 'contract must warn read-only is not always enforced');
});

test('codex P2b: render is env-neutral (HOPPER_CLAUDE_BARE does not leak --bare into the doc)', () => {
  const prev = process.env.HOPPER_CLAUDE_BARE;
  process.env.HOPPER_CLAUDE_BARE = '1';
  try {
    const md = renderRulesMarkdown();
    assert.ok(!/claude .*--bare/.test(md), 'env-affected flags must be neutralized for a deterministic doc');
  } finally {
    if (prev === undefined) delete process.env.HOPPER_CLAUDE_BARE; else process.env.HOPPER_CLAUDE_BARE = prev;
  }
});

test('scaffold writes .hopper/DISPATCH.md with the generated matrix', () => {
  const dispatch = buildScaffoldFiles().find((f) => f.rel === 'DISPATCH.md');
  assert.ok(dispatch, 'scaffold must include DISPATCH.md');
  assert.match(dispatch.content, /Per-vendor capability matrix/);
  for (const v of listAdapters()) {
    assert.match(dispatch.content, new RegExp(`\\|\\s*${v}\\s*\\|`));
  }
});

test('scaffold AGENTS.md carries the constitution pointer AND still parses', () => {
  const agentsFile = buildScaffoldFiles().find((f) => f.rel === 'AGENTS.md');
  assert.match(agentsFile.content, /\.hopper\/DISPATCH\.md/);
  assert.match(agentsFile.content, /GENERATED from the hopper adapters/);
  // The added prose must not break the vendor-routing parser.
  const agents = parseAgentsContent(agentsFile.content);
  assert.equal(resolveVendor({ taskType: 'code-impl', vendor: null }, agents), 'kimi');
});
